### ISSUE TITLE
Global namespace

### ISSUE THREAD

**Issue by Etiene** [ezerfernandes/funkmoon#1]
Hello ezer! This looks awesome!

I have a design recommendation for you: avoid using the global namespace!
It's bad practice as it may cause conflicts when using different modules

Here goes a preferred way to create a module in Lua:

```
local my_module = {}

function my_module.a_func()
    ...
end

return my_module
```

or

```
local function a_func()
    ...
end

return {a_func = a_func}
```

+

```
local mm = require "my_module"

mm.a_func()
```

Good job on your studies and have fun 🐰

PS: you should consider uploading this to LuaRocks once you're done :)

**Comment by ezerfernandes** [comment]
Hello Etiene, thanks for your suggestions, I'm going to apply them all!

I started learning Lua in december and I'm loving it! Although I came from a Python and C# background, I'm studying Scala and I stole a lot of ideas from it :)

Do you want to be a contributor in the project? I'm new to creating open source projects here and your contributions would be very welcomed :)

Do you speak portuguese? I was also from Rio but I live in Brasília now.

PS: What is LuaRocks? Let's see :)

**Comment by Etiene** [comment]
Sim eu falo português! Prefere que eu fale em pt?

Não estou com muito tempo pra ficar contribuindo! O meu projeto já dá bastante trabalho hahahaha 
(http://github.com/sailorproject <= inclusive se quiser ir lá dar uma mãozinha)
Mas vou ajudar no que puder :) 

LuaRocks é o package manager de Lua. Vai ser útil se você quiser publicar seu módulo pra outras pessoas instalarem e usarem. Para isso você vai precisar de um arquivo .rockspec que vc faz upload em http://luarocks.org

Eu tenho um módulo de um arquivo só também, dá uma olhada caso você queira usar a estrutura de exemplo: https://github.com/sailorproject/valua

Yay :dancers:

**Comment by ezerfernandes** [comment]
Etiene, resolvi os problemas que vc apontou e fiz mais alguns ajustes :) Obrigado pelas sugestões =)
